name: DiT_eval       # <--- [修改] 改个新名字，防止覆盖旧环境
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.11      # <--- [修改] 强制锁定 3.11
  - pytorch >= 1.13
  - torchvision
  - pytorch-cuda=11.7
  - pip:
    - timm
    - diffusers
    - accelerate
    - scipy          # <--- [新增] 加上这个，以后评估可能用到